### ISSUE TITLE
Fatigue Stress - Experiment

### ISSUE THREAD

**Issue by narenakash** [virtual-labs/basic-engineering-mechanics-and-strength-of-materials-iiith#114] opened 2019-03-17 16:54 UTC
**Description**
The link to the experiment redirects it to a wrong page.

**Expected Behavior**
The link given on the page should take it to the VLabs Experiment page.

**Actual Behavior**
The link redirects it to https://www.oracle.com/technetwork/java/index.html page.

*Link to the page:* http://eerc01-iiith.vlabs.ac.in/exp7/Experiment.html?domain=Civil%20Engineering&lab=Basic%20Engineering%20Mechanics%20&%20Strength%20of%20Materials%20Lab
![Screenshot from 2019-03-17 22-24-19](https://user-images.githubusercontent.com/43748290/54494732-6e8d6300-4903-11e9-831d-b741c8b329d0.png)

**Comment by LSAITHARUN** [comment] 2019-03-31 18:38
fixed
commit id : a212f54

**Comment by sravanthimodepu** [comment] 2019-05-01 09:11
Required Java to run the simulation, if it is installed then the link redirects to the simulation else to Oracle page to download and install Java.

The issue is not valid, hence closing the issue.

**Closed by sravanthimodepu** 2019-05-01 09:11 UTC
